version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    command: ["/usr/wait-for-mariadb.sh", "mariadb", "node", "/usr/src/app/index.js"]
      
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rania
      MYSQL_DATABASE: userdb
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mariadb-data:

