version: '3'

services:
  web:
    build: .
    image: nodejs:latest
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    command: ["/usr/wait-for-mariadb.sh", "mariadb", "node", "/usr/src/app/index.js"]
    networks:
      - app_network
      
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rania
      MYSQL_DATABASE: userdb
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

volumes:
  mariadb-data:
  
networks:
  app_network:
