apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: haddaouirania/mariadb_container:latest
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rania
        - name: MYSQL_DATABASE
          value: userdb
        ports:
        - containerPort: 3306
          name: mariadb
      imagePullSecrets:
      - name: jenkins-ssh-key

